<?xml version="1.0" encoding="UTF-8"?>
<project default="clean" basedir="." name="lucee-tasks-extension">
    <description>Build process for the Quartz extension</description>
    
   
    <!-- path definitions -->
    <property name="src" location="source"/>
    <property name="srcCFML" location="source/cfml"/>
    <property name="srcImg" location="source/images"/>
    <property name="jars" location="jars"/>
    <property name="temp" location="temp"/>
    <property name="target" location="target"/>
    <property name="maven.dir" location="${temp}/maven"/>
    <property name="maven.goal" value="package"/>
    
    <target name="init" description="initialize the environment">
        <delete dir="${temp}"/>
        <delete dir="${target}"/>
        <mkdir dir="${temp}"/>
        <mkdir dir="${target}/"/>
        <mkdir dir="${maven.dir}"/>
        <mkdir dir="${src}/config" />
    </target>

    <target name="maven-deps" depends="init" description="download dependencies using Maven">
        <!-- First build the project -->
        <exec dir="." executable="mvn" failonerror="true">
            <arg line="-f maven-dependencies.xml clean ${maven.goal} -Drevision=${bundleversion}"/>
        </exec>
        
        <!-- Copy all dependencies -->
        <exec dir="." executable="mvn" failonerror="true">
            <arg value="-f"/>
            <arg value="maven-dependencies.xml"/>
            <arg value="dependency:copy-dependencies"/>
            <arg value="-DoutputDirectory=${maven.dir}"/>
            <arg value="-Dmdep.copyPom=true"/>
            <arg value="-DexcludeScope=provided"/>
            <arg value="-Drevision=${bundleversion}"/>
            <arg value="-Dmdep.useRepositoryLayout=true"/>
        </exec>

        <!-- Clean up Maven build artifacts -->
        <delete dir="target"/>
    </target>
    
    <target name="createManifest" depends="maven-deps" description="create Manifest file">
        <tstamp>
            <format property="NOW" pattern="yyyy-MM-dd HH:mm:ss"/>
        </tstamp>
        <echo file="${temp}/META-INF/MANIFEST.MF">Manifest-Version: 1.0
Built-Date: ${NOW}
version: "${bundleversion}"
id: "${id}"
name: "${label}"
description: "${description}"
lucee-core-version: "${luceeCoreVersion}"
event-gateway-instance: "[{'cfcPath':'${cfc-path}','id':'${task-instance-name}','readOnly':false,'startupMode':'automatic','custom':{'configFile':'${config-file}','logName':'scheduler'}}]"
</echo>
    </target>
    
    <target name="zip" depends="createManifest" description="generate the distribution">
        <!-- copy the logo -->
        <copy todir="${temp}/META-INF">
            <fileset dir="${srcImg}/">
                <include name="logo.png"/>
            </fileset>
        </copy>
        <!-- copy the components -->
        <copy todir="${temp}/components">
            <fileset dir="${src}/components">
                <include name="**/*.cfc"/>
            </fileset>
        </copy>
        <!-- copy the event-gateway -->
        <copy todir="${temp}/event-gateways">
            <fileset dir="${src}/event-gateways">
                <include name="**/*.cfc"/>
            </fileset>
        </copy>
        <!-- this is necessary because of a bug in the lucee core -->
        <copy todir="${temp}/event-gateway">
            <fileset dir="${src}/event-gateways">
                <include name="**/*.cfc"/>
            </fileset>
        </copy>
        <!-- copy the web context -->
        <copy todir="${temp}/config">
            <fileset dir="${src}/config">
                <include name="**/*.*"/>
            </fileset>
        </copy>
        <copy todir="${temp}/context">
            <fileset dir="${src}/context">
                <include name="**/*.*"/>
            </fileset>
        </copy>
        <!-- Zip everything -->
        <zip destfile="${target}/${filename}-${bundleversion}.lex">
            <zipfileset dir="${temp}"/>
        </zip>
    </target>
    
    <target name="clean" depends="zip" description="clean up">
        <!-- <delete dir="${temp}"/> -->
    </target>
</project>